### ISSUE TITLE
System.NullReferenceException is thrown if RuntimeIdentifier is "linux-arm64".

### ISSUE THREAD

**Issue by Andre-Loetzsch** [Andre-Loetzsch/AssemblyVersioning#54]
Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Oleander.Assembly.Versioning.AssemblyFrameworkInfo..ctor(String assemblyLocation)
   at Oleander.Assembly.Versioning.Versioning.TryGetAssemblyFrameworkInfo(FileInfo assemblyLocationFileInfo, AssemblyFrameworkInfo& assemblyFrameworkInfo)
   at Oleander.Assembly.Versioning.Versioning.ValidateFileSystem()
   at Oleander.Assembly.Versioning.Versioning.UpdateAssemblyVersion(String targetFileName, String projectDirName, String projectFileName, String gitRepositoryDirName)
   at Oleander.Assembly.Versioning.BuildTask.VersioningTask.InnerExecute()
   at Oleander.Assembly.Versioning.BuildTask.VersioningTask.Execute()

**Comment by Andre-Loetzsch** [comment]
Do not use the base cache directory as a path for log files
